using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class PlayerControl : MonoBehaviour {

	public List<Transform> Platform;
	private float speed= 0.5f;
	public CharacterController player;
	private Vector3 moveDirection = Vector3.zero;
	private Vector3 pMov;
	public float jumpSpeed = 1.0f;
	private float gravity = 10f;
	float playerZposition;
	private bool isGrounded;
	private float pSpeed = 10f;
	public GameObject ScoreAndSpawnrate; // external object to manage dificulty


	Bounds _bounds;
	Transform lastPlatform;

	List<Transform> platforms = new List<Transform>();


	void Start () {

		for(int i = 0;i < 20; i++){

			Transform platform = (Transform)Instantiate(Platform[Random.Range(0,Platform.Count)]);

			if(i > 0){
				Bounds prevbounds = platforms[i - 1].FindChild("Surface").GetComponent<MeshRenderer>().bounds;
				Bounds bounds = platform.FindChild("Surface").GetComponent<MeshRenderer>().bounds;

				platform.transform.position = platforms[i - 1].position + new Vector3(0,0,bounds.extents.z + prevbounds.extents.z); 

				_bounds = bounds;
			}else{
				platform.transform.position = Vector3.zero;
			}


			platforms.Add(platform);
		}
	}


	void FixedUpdate(){

		playerZposition = player.transform.position.z;
		player.transform.position += new Vector3 (0, 0, speed);
		pMov = new Vector3 (Input.GetAxis ("Horizontal") * pSpeed , 0, 0);
		
		if (player.isGrounded) {
			player.SimpleMove (pMov);	
			player.GetComponent<Animation>().Play ("run");
			
		}
		
		if (Input.GetButton ("Jump") && player.isGrounded) {
			isGrounded = false;
			player.GetComponent<Animation> ().Stop ("run");
			player.GetComponent<Animation> ().Play ("jump_pose");
			moveDirection.y = jumpSpeed / 3f;
		}
		
		player.Move (moveDirection);
		moveDirection.y -= gravity * .25f * Time.deltaTime;
		
		if (player.isGrounded)
			isGrounded = true;
		//moveDirection.y -= gravity * Time.deltaTime;
 		//player.Move (moveDirection * Time.deltaTime);


		for(int i = 0;i < platforms.Count; i++){
			if(platforms[i].position.z < transform.position.z - _bounds.extents.z){
				Destroy(platforms[i].gameObject);
				platforms.RemoveAt(i);
				
				
				
				Transform platform = (Transform)Instantiate(Platform[Random.Range(0,Platform.Count)]);
				
				Bounds prevbounds = platforms[platforms.Count - 1].FindChild("Surface").GetComponent<MeshRenderer>().bounds;
				Bounds bounds = platform.FindChild("Surface").GetComponent<MeshRenderer>().bounds;
				
				platform.transform.position = platforms[platforms.Count - 1].position + new Vector3(0,0,bounds.extents.z + prevbounds.extents.z); 
				
				_bounds = bounds;
				
				platforms.Add(platform);
				
				break;
				//platforms[i].position = lastPlatform.position + new Vector3(0,0,_bounds.extents.z * 2);
				//lastPlatform = platforms[i];
			}
		}

		transform.position += transform.forward *.5f;

		if (ScoreAndSpawnrate.GetComponent<GameControlScript> ().score > 1500) {
			ScoreAndSpawnrate.GetComponent<SpawnScript>().spawnCycle = 0.35f;
			transform.position += transform.forward * .1f;
			speed = 0.6f;
		}

		if (ScoreAndSpawnrate.GetComponent<GameControlScript> ().score > 300) {
			ScoreAndSpawnrate.GetComponent<SpawnScript>().spawnCycle = 0.3f;
			transform.position += transform.forward * .2f;
			speed = 0.7f;
		} 

		if (ScoreAndSpawnrate.GetComponent<GameControlScript> ().score > 450) {
			ScoreAndSpawnrate.GetComponent<SpawnScript>().spawnCycle = 0.2f;
			transform.position += transform.forward * .2f;
			speed = 0.8f;
		} 

		if (ScoreAndSpawnrate.GetComponent<GameControlScript> ().score > 600) {
			ScoreAndSpawnrate.GetComponent<SpawnScript>().spawnCycle = 0.15f;
			transform.position += transform.forward * .2f;
			speed = 0.9f;
		} 

		 if (ScoreAndSpawnrate.GetComponent<GameControlScript> ().score > 900) {
			ScoreAndSpawnrate.GetComponent<SpawnScript>().spawnCycle = 0.1f;
			transform.position += transform.forward * 0.2f;
			speed = 1.0f;
		} 
	}
}